#!/usr/bin/env bash
# Function to handle SIGTERM signal
terminate() {
    echo "I am invincible!!!"
    exit 0
}

# Register the terminate function for SIGTERM
trap 'terminate' SIGTERM

# Main loop to display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 2
done